# Generated by Django 4.2.13 on 2024-05-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('arrive_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
